### ISSUE TITLE
lootbags are immovable .. annoying

### ISSUE THREAD

**Issue by HarvJen** [London-Gaming-Network/server-issues#13]
**What Is The Issue?** - loot bags cannot be moved and are stuck in the location that they spawn , this can be annoying especially if they are in the middle of the road as it just stops and breaks cars in their tracks

**How Do You Reproduce This Error** - hit a lootbag 

**What Is Meant To Happen** -  not that , they should move or something

**Screenshots/Video** - https://www.youtube.com/watch?v=SpU25Xo48rA

**Comment by Vibe-The-Dev** [comment]
this isn't a bug its simply that the person whomade it made it with collisions
